const {StyleSheet} = require('react-native');
const {
  windowWidth,
  widthToDp,
  adjustedFontSize,
} = require('../../../Utils/dimensionsInPixel');

const styles1 = StyleSheet.create({
  container1: {
    width: windowWidth * (80 / 100),
    marginVertical: widthToDp(1),
    paddingVertical: widthToDp(1),
    paddingHorizontal: widthToDp(2),
    borderRadius: 10,
  },
  container2: {
    justifyContent: 'center',
    alignItems: 'center',
    // paddingVertical: widthToDp(1),
  },
  title1: {
    fontSize: adjustedFontSize(12),
    fontWeight: '500',
  },
  container3: {
    borderWidth: widthToDp(0.5),
    borderRadius: 10,
    paddingHorizontal: widthToDp(2),
    paddingVertical: widthToDp(2),
    marginVertical: widthToDp(2),
  },
  title2: {
    fontSize: adjustedFontSize(12),
    fontWeight: '500',
  },
  container4: {
    flexDirection: 'row',
    marginRight: widthToDp(3),
    marginLeft: widthToDp(5),
    paddingVertical: widthToDp(1),
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  title3: {
    fontSize: adjustedFontSize(11),
    fontWeight: '400',
  },
  container5: {
    flexDirection: 'row',
    marginLeft: widthToDp(3),
    borderWidth: widthToDp(0.5),
    borderRadius: 8,
    paddingVertical: widthToDp(2),
    paddingHorizontal: widthToDp(4),
    justifyContent: 'center',
    alignItems: 'center',
  },
  title4: {
    fontSize: adjustedFontSize(9.5),
    fontWeight: '400',
    paddingLeft: widthToDp(2),
  },
  container6: {
    flexDirection: 'row',
    marginTop: widthToDp(3),
    justifyContent: 'space-evenly',
    alignItems: 'center',
    paddingVertical: widthToDp(3),
    borderTopWidth: widthToDp(0.6),
  },
  btn1: {
    paddingVertical: widthToDp(2),
    borderWidth: widthToDp(0.5),
    borderColor: 'blue',
    paddingHorizontal: widthToDp(8),
    borderRadius: 10,
  },
  btn2: {
    paddingHorizontal: widthToDp(8),
    backgroundColor: '#00d9ff',
    paddingVertical: widthToDp(2.4),
    borderRadius: 10,
  },
  btn3: {
    paddingLeft: widthToDp(2),
  },
});

const styles2 = StyleSheet.create({
  container1: {
    flex: 1,
    backgroundColor: '#005266aa',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: widthToDp(1),
  },
  container2: {
    width: '100%',
    paddingVertical: widthToDp(5),
    borderRadius: 10,
  },
  container3: {
    marginLeft: widthToDp(3),
    height: widthToDp(10),
    width: widthToDp(35),
    borderWidth: widthToDp(0.5),
    borderRadius: 12,
    padding: widthToDp(2),
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.2,
    shadowRadius: 1.41,
    elevation: 2,
  },
  title1: {
    fontSize: adjustedFontSize(10),
    fontWeight: '400',
    paddingHorizontal: widthToDp(3),
  },
  container4: {
    marginLeft: widthToDp(3),
    paddingHorizontal: widthToDp(2),
    height: widthToDp(10),
    width: widthToDp(35),
    borderWidth: widthToDp(0.5),
    borderRadius: 12,
    shadowColor: '#000',
    justifyContent: 'center',
    alignItems: 'center',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.2,
    shadowRadius: 1.41,
    elevation: 2,
  },
  inputStyles: {
    fontSize: adjustedFontSize(10),
    height: widthToDp(10),
    justifyContent: 'center',
    alignItems: 'center',
  },
  container5: {
    marginLeft: widthToDp(3),
    height: widthToDp(10),
    width: widthToDp(35),
    borderWidth: widthToDp(0.5),
    borderRadius: 12,
    padding: widthToDp(2),
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.2,
    shadowRadius: 1.41,
    elevation: 2,
  },
  title2: {
    paddingLeft: widthToDp(2),
    fontSize: adjustedFontSize(10),
  },
  rightIconStyle: {
    width: widthToDp(5.5),
    height: widthToDp(5.5),
  },
  container6: {
    marginHorizontal: widthToDp(5),
    paddingHorizontal: widthToDp(2),
    height: widthToDp(10),
    width: widthToDp(40),
    borderWidth: widthToDp(0.5),
    borderRadius: 12,
    shadowColor: '#000',
    justifyContent: 'center',
    alignItems: 'center',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.2,
    shadowRadius: 1.41,
    elevation: 2,
  },
  inputStyles2: {
    fontSize: adjustedFontSize(10),
    height: widthToDp(10),
    justifyContent: 'center',
    alignItems: 'center',
  },
  container7: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: widthToDp(2),
  },
  btn1: {
    paddingHorizontal: widthToDp(5),
    paddingVertical: widthToDp(3),
    borderWidth: widthToDp(0.8),
    borderColor: 'blue',
    borderRadius: 20,
  },
  btn2: {
    backgroundColor: '#00d9ff',
    paddingHorizontal: widthToDp(6),
    paddingVertical: widthToDp(3.5),
    borderRadius: 20,
  },
});

export {styles1, styles2};
