const ApiConstants = {
  UPDATE_LODING_STATE: 'UPDATE_LODING_STATE',
  RESET_APP_DATA: 'RESET_APP_DATA',

  //Authentication
  API_SIGNUP_LOAD: 'API_SIGNUP_LOAD',
  API_SIGNUP_ERROR: 'API_SIGNUP_ERROR',
  API_SIGNUP_SUCCESS: 'API_SIGNUP_SUCCESS',

  API_LOGIN_LOAD: 'API_LOGIN_LOAD',
  API_LOGIN_ERROR: 'API_LOGIN_ERROR',
  API_LOGIN_SUCCESS: 'API_LOGIN_SUCCESS',

  API_FORGET_PASSWORD_LOAD: 'API_FORGET_PASSWORD_LOAD',
  API_FORGET_PASSWORD_ERROR: 'API_FORGET_PASSWORD_ERROR',
  API_FORGET_PASSWORD_SUCCESS: 'API_FORGET_PASSWORD_SUCCESS',

  API_VERIFY_OTP_LOAD: 'API_VERIFY_OTP_LOAD',
  API_VERIFY_OTP_ERROR: 'API_VERIFY_OTP_ERROR',
  API_VERIFY_OTP_SUCCESS: 'API_VERIFY_OTP_SUCCESS',

  API_NEW_PASSWORD_LOAD: 'API_NEW_PASSWORD_LOAD',
  API_NEW_PASSWORD_ERROR: 'API_NEW_PASSWORD_ERROR',
  API_NEW_PASSWORD_SUCCESS: 'API_NEW_PASSWORD_SUCCESS',

  API_CONFIRM_SIGNUP_OTP_LOAD: 'API_CONFIRM_SIGNUP_OTP_LOAD',
  API_CONFIRM_SIGNUP_OTP_SUCCESS: 'API_CONFIRM_SIGNUP_OTP_SUCCESS',
  API_CONFIRM_SIGNUP_OTP_ERROR: 'API_CONFIRM_SIGNUP_OTP_ERROR',

  API_FORGOT_PASSWORD_LOAD: 'API_FORGOT_PASSWORD_LOAD',
  API_FORGOT_PASSWORD_SUCCESS: 'API_FORGOT_PASSWORD_SUCCESS',

  LOGOUT_AUTH: 'LOGOUT_AUTH',

  //Services
  API_GET_DOC_LIST_LOAD: 'API_GET_DOC_LIST_LOAD',
  API_GET_DOC_LIST_SUCCESS: 'API_GET_DOC_LIST_SUCCESS',
  API_GET_DOC_LIST_ERROR: 'API_GET_DOC_LIST_ERROR',

  API_PHYSICIAN_LIST_LOAD: 'API_PHYSICIAN_LIST_LOAD',
  API_PHYSICIAN_LIST_SUCCESS: 'API_PHYSICIAN_LIST_SUCCESS',
  API_PHYSICIAN_LIST_ERROR: 'API_PHYSICIAN_LIST_ERROR',

  API_SURGEON_LIST_LOAD: 'API_SURGEON_LIST_LOAD',
  API_SURGEON_LIST_SUCCESS: 'API_SURGEON_LIST_SUCCESS',
  API_SURGEON_LIST_ERROR: 'API_SURGEON_LIST_ERROR',

  API_THERAPIST_LIST_LOAD: 'API_THERAPIST_LIST_LOAD',
  API_THERAPIST_LIST_SUCCESS: 'API_THERAPIST_LIST_SUCCESS',
  API_THERAPIST_LIST_ERROR: 'API_THERAPIST_LIST_ERROR',

  API_DOCTOR_DETAILS_LOAD: 'API_DOCTOR_DETAILS_LOAD',
  API_DOCTOR_DETAILS_SUCCESS: 'API_DOCTOR_DETAILS_SUCCESS',
  API_DOCTOR_DETAILS_ERROR: 'API_DOCTOR_DETAILS_ERROR',

  API_THERAPIST_DETAILS_LOAD: 'API_THERAPIST_DETAILS_LOAD',
  API_THERAPIST_DETAILS_SUCCESS: 'API_THERAPIST_DETAILS_SUCCESS',
  API_THERAPIST_DETAILS_ERROR: 'API_THERAPIST_DETAILS_ERROR',

  API_DOCTOR_TODAY_SLOT_LOAD: 'API_DOCTOR_TODAY_SLOT_LOAD',
  API_DOCTOR_TODAY_SLOT_SUCCESS: 'API_DOCTOR_TODAY_SLOT_SUCCESS',
  API_DOCTOR_TODAY_SLOT_ERROR: 'API_DOCTOR_TODAY_SLOT_ERROR',

  API_THERAPIST_TODAY_SLOT_LOAD: 'API_THERAPIST_TODAY_SLOT_LOAD',
  API_THERAPIST_TODAY_SLOT_SUCCESS: 'API_THERAPIST_TODAY_SLOT_SUCCESS',
  API_THERAPIST_TODAY_SLOT_ERROR: 'API_THERAPIST_TODAY_SLOT_ERROR',

  API_DOCTOR_ALL_ONLINE_SLOT_LOAD: 'API_DOCTOR_TODAY_SLOT_LOAD',
  API_DOCTOR_ALL_ONLINE_SLOT_SUCCESS: 'API_DOCTOR_TODAY_SLOT_SUCCESS',
  API_DOCTOR_ALL_ONLINE_SLOT_ERROR: 'API_DOCTOR_TODAY_SLOT_ERROR',

  API_DOCTOR_ALL_OFFLINE_SLOT_LOAD: 'API_DOCTOR_ALL_OFFLINE_SLOT_LOAD',
  API_DOCTOR_ALL_OFFLINE_SLOT_SUCCESS: 'API_DOCTOR_TODAY_SLOT_SUCCESS',
  API_DOCTOR_ALL_OFFLINE_SLOT_ERROR: 'API_DOCTOR_ALL_OFFLINE_SLOT_ERROR',

  API_THERAPIST_ALL_ONLINE_SLOT_LOAD: 'API_THERAPIST_ALL_ONLINE_SLOT_LOAD',
  API_THERAPIST_ALL_ONLINE_SLOT_SUCCESS:
    'API_THERAPIST_ALL_ONLINE_SLOT_SUCCESS',
  API_THERAPIST_ALL_ONLINE_SLOT_ERROR: 'API_THERAPIST_ALL_ONLINE_SLOT_ERROR',

  API_THERAPIST_ALL_OFFLINE_SLOT_LOAD: 'API_THERAPIST_ALL_OFFLINE_SLOT_LOAD',
  API_THERAPIST_ALL_OFFLINE_SLOT_SUCCESS:
    'API_THERAPIST_ALL_OFFLINE_SLOT_SUCCESS',
  API_THERAPIST_ALL_OFFLINE_SLOT_ERROR: 'API_THERAPIST_ALL_OFFLINE_SLOT_ERROR',

  //Others
  ON_CHANGE_THEME: 'ON_CHANGE_THEME',
};

//SUCCESS
//ERROR
export default ApiConstants;
