const ApiConstants = {
  UPDATE_LODING_STATE: 'UPDATE_LODING_STATE',
  RESET_APP_DATA: 'RESET_APP_DATA',
  //Authentication
  API_SIGNUP_LOAD: 'API_SIGNUP_LOAD',
  API_SIGNUP_ERROR: 'API_SIGNUP_ERROR',
  API_SIGNUP_SUCCESS: 'API_SIGNUP_SUCCESS',
  API_LOGIN_LOAD: 'API_LOGIN_LOAD',
  API_LOGIN_ERROR: 'API_LOGIN_ERROR',
  API_LOGIN_SUCCESS: 'API_LOGIN_SUCCESS',
  API_FORGET_PASSWORD_LOAD: 'API_FORGET_PASSWORD_LOAD',
  API_FORGET_PASSWORD_ERROR: 'API_FORGET_PASSWORD_ERROR',
  API_FORGET_PASSWORD_SUCCESS: 'API_FORGET_PASSWORD_SUCCESS',
  API_VERIFY_OTP_LOAD: 'API_VERIFY_OTP_LOAD',
  API_VERIFY_OTP_ERROR: 'API_VERIFY_OTP_ERROR',
  API_VERIFY_OTP_SUCCESS: 'API_VERIFY_OTP_SUCCESS',
  API_NEW_PASSWORD_LOAD: 'API_NEW_PASSWORD_LOAD',
  API_NEW_PASSWORD_ERROR: 'API_NEW_PASSWORD_ERROR',
  API_NEW_PASSWORD_SUCCESS: 'API_NEW_PASSWORD_SUCCESS',
  API_CONFIRM_SIGNUP_OTP_LOAD: 'API_CONFIRM_SIGNUP_OTP_LOAD',
  API_CONFIRM_SIGNUP_OTP_SUCCESS: 'API_CONFIRM_SIGNUP_OTP_SUCCESS',
  API_CONFIRM_SIGNUP_OTP_ERROR: 'API_CONFIRM_SIGNUP_OTP_ERROR',
  API_FORGOT_PASSWORD_LOAD: 'API_FORGOT_PASSWORD_LOAD',
  API_FORGOT_PASSWORD_SUCCESS: 'API_FORGOT_PASSWORD_SUCCESS',
  LOGOUT_AUTH: 'LOGOUT_AUTH',

  //Others
  ON_CHANGE_THEME: 'ON_CHANGE_THEME',
};

export default ApiConstants;
